# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Create_date',
            new_name='created_date',
        ),
    ]
